# Postgres Driver
spring.datasource.driver=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

app.init.dailyList=AAPL,MSFT,GOOG

finnhub.api.base-url=https://finnhub.io/api/v1
finnhub.api.token=da8qajpr01qvfj5thvdgda8qajpr01qvfj5thve0