package ca.jrvs.apps.trading.service;

import ca.jrvs.apps.trading.ExceptionUtil;
import ca.jrvs.apps.trading.ResourceNotFoundException;
import ca.jrvs.apps.trading.dto.Account;
import ca.jrvs.apps.trading.dto.Position;
import ca.jrvs.apps.trading.dto.Trader;
import ca.jrvs.apps.trading.dto.TraderAccountView;
import ca.jrvs.apps.trading.repository.AccountJpaRepoDao;
import ca.jrvs.apps.trading.repository.PositionJpaRepoDao;
import ca.jrvs.apps.trading.repository.SecurityOrderJpaRepoDao;
import ca.jrvs.apps.trading.repository.TraderJpaRepoDao;
import java.util.Arrays;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class TraderAccountService {

    private final TraderJpaRepoDao traderJpaRepoDao;

    private final AccountJpaRepoDao accountJpaRepoDao;

    private final PositionJpaRepoDao positionJpaRepoDao;

    private final SecurityOrderJpaRepoDao securityOrderJpaRepoDao;

    @Autowired
    public TraderAccountService(AccountJpaRepoDao accountJpaRepoDao, TraderJpaRepoDao traderJpaRepoDao,
        PositionJpaRepoDao positionJpaRepoDao, SecurityOrderJpaRepoDao securityOrderJpaRepoDao) {
        this.accountJpaRepoDao = accountJpaRepoDao;
        this.traderJpaRepoDao = traderJpaRepoDao;
        this.positionJpaRepoDao = positionJpaRepoDao;
        this.securityOrderJpaRepoDao = securityOrderJpaRepoDao;
    }

    public static <T> boolean allFilled(T obj){
        return Arrays.stream(obj.getClass().getDeclaredFields())
            .filter(f -> !f.getName().equals("id"))
            .peek(f -> f.setAccessible(true))
            .allMatch(f -> {
                try {
                    Object v = f.get(obj);
                    return v != null && !v.toString().trim().isEmpty();
                } catch (IllegalAccessException e) {
                    return false;
                }
            });
    }
    /**
     * Create a new trader and initialize a new account with 0 amount
     * - validate user input (all fields must be non empty)
     * - create a trader
     * - create an account
     * - create, setup, and return a new traderAccountView
     * Assumption: to simplify the logic, each trader has only one account where traderId == accountId
     *
     * @param trader cannot be null. All fields cannot be null except for id (auto-generated by db)
     * @return traderAccountView
     * @throws IllegalArgumentException if a trader has null fields or id is not null
     */
    public TraderAccountView createTraderAndAccount(Trader trader) {
        if(!allFilled(trader)){
            throw new IllegalArgumentException(
                ExceptionUtil.buildMessage("Trader cannot contain empty fields, excluding id")
            );
        }
        Account account = new  Account();
        account.setTraderId(trader.getId());
        account.setAmount(0.0);
        try{
            traderJpaRepoDao.save(trader);
            accountJpaRepoDao.save(account);
        }catch(Exception e){
            throw new RuntimeException(ExceptionUtil.buildMessage("unable to save traderAccountView"));
        }

        return new TraderAccountView(trader, account);

    }

    /**
     * A trader can be deleted if and only if it has no open position and 0 cash balance
     * - validate traderId
     * - get trader account by traderId and check account balance
     * - get positions by accountId and check positions
     * - delete all securityOrders, account, trader (in this order)
     *
     * @param traderId must not be null
     * @throws IllegalArgumentException if traderId is null or not found or unable to delete
     */
    public void deleteTraderById(Integer traderId) {
        if(traderId == null){
            throw new IllegalArgumentException(ExceptionUtil.buildMessage("traderId cannot be null"));
        }

        Optional<Trader> opTrader = traderJpaRepoDao.findById(traderId);

        if(!opTrader.isPresent()){
            throw new ResourceNotFoundException(ExceptionUtil.buildMessage("traderId not found"));
        }
        Trader trader = opTrader.get();
        Account account = new  Account();
        Optional<Account> opAccount = accountJpaRepoDao.findById(trader.getId());
        if(!opAccount.isPresent()){
            throw new ResourceNotFoundException(ExceptionUtil.buildMessage(String.format("account from trader with id %s not found",  trader.getId())));

        }
        account = opAccount.get();
        if (account.getAmount() != 0.0){
            throw new IllegalStateException(ExceptionUtil.buildMessage(String.format("account from trader with id %s contains funds", trader.getId())));
        }

        Position position;
        Optional<Position> optionalPosition = positionJpaRepoDao.findById(account.getId());

        if(!optionalPosition.isPresent()){
            throw new ResourceNotFoundException(ExceptionUtil.buildMessage(String.format("position with account id %s not found", account.getId())));
        }

        position = optionalPosition.get();
        if (position.getPosition() > 0){
            throw new IllegalStateException(ExceptionUtil.buildMessage(String.format("Trader with id %s contains open positions", trader.getId())));
        }


        try{
            securityOrderJpaRepoDao.deleteById(trader.getId());
            accountJpaRepoDao.deleteById(account.getId());
            traderJpaRepoDao.deleteById(trader.getId());

        }catch (Exception e){
            throw new RuntimeException(ExceptionUtil.buildMessage("unable to delete trader account"));
        }

    }

    /**
     * Deposit a fund to an account by traderId
     * - validate user input
     * - find account by trader id
     * - update the amount accordingly
     *
     * @param traderId must not be null
     * @param fund must be greater than 0
     * @return updated Account
     * @throws IllegalArgumentException if traderId is null or not found,
     * 									and fund is less than or equal to 0
     */
    public Account deposit(Integer traderId, Double fund) {
        Optional<Trader> opTrader = traderJpaRepoDao.findById(traderId);
        if(!opTrader.isPresent()){
            throw new ResourceNotFoundException(ExceptionUtil.buildMessage("trader with id " + traderId + " not found"));
        }
        if (fund <=  0.0){
            throw new IllegalStateException(ExceptionUtil.buildMessage("fund must be greater than zero"));
        }


        Optional<Account> optionalAccount = accountJpaRepoDao.findById(traderId);
        if(!optionalAccount.isPresent()){
            throw new ResourceNotFoundException(ExceptionUtil.buildMessage(String.format("account with id %s not found", traderId)));
        }
        Account account = optionalAccount.get();
        account.setAmount(account.getAmount() + fund);
        accountJpaRepoDao.save(account);
        return account;
    }

    /**
     * Withdraw a fund to an account by traderId
     * - validate user input
     * - find account by trader id
     * - update the amount accordingly
     *
     * @param traderId must not be null
     * @param fund must be greater than 0
     * @return updated Account
     * @throws IllegalArgumentException if traderId is null or not found,
     * 									and fund is less than or equal to 0
     */
    public Account withdraw(Integer traderId, Double fund) {
        if(traderId == null){
            throw new IllegalArgumentException(ExceptionUtil.buildMessage("traderId cannot be null"));
        }
        if(fund <=  0.0){
            throw new IllegalStateException(ExceptionUtil.buildMessage("fund must be greater than zero"));
        }

        Optional<Account> optionalAccount = accountJpaRepoDao.findById(traderId);
        if(!optionalAccount.isPresent()){
            throw new ResourceNotFoundException(ExceptionUtil.buildMessage(String.format("account with id %s not found", traderId)));
        }

        Account account = optionalAccount.get();
        account.setAmount(account.getAmount() - fund);
        accountJpaRepoDao.save(account);
        return account;
    }
}
